# server settings
server:
  # your ip address where the server will run
  host: "localhost"

  # port where the server will listen
  port: "8000"

# database settings
database:
  # the database host (domain/ip)
  host: "devserver"

  # the port where the database is listening (usually 3306)
  port: "3306"

  # the database user
  user: "root"

  # the database user's password
  password: "root"

  # the database name
  name: "boleiro"